from components.styles.styles import (
    CANVAS_BG,
    FONT_FAMILY,
    SELECTED_OUTLINE,
    TEXT_DARK,
    TEXT_LIGHT,
)
from components.shared.paths import resource_path


WINDOW_WIDTH = 900
WINDOW_HEIGHT = 700
WINDOW_MIN_WIDTH = 720
WINDOW_MIN_HEIGHT = 520

CANVAS_MIN_WIDTH = 100
CANVAS_DEFAULT_WIDTH = 800
CANVAS_PADDING = 40
PDF_CANVAS_BG = CANVAS_BG

ZOOM_MIN = 0.3
ZOOM_MAX = 3.0
ZOOM_STEP = 0.1

CONCEPT_DIALOG_WIDTH = 520
CONCEPT_DIALOG_HEIGHT = 520
CONCEPT_DIALOG_MIN_WIDTH = 520
CONCEPT_DIALOG_MIN_HEIGHT = 520

LISTBOX_HEIGHT = 9
LISTBOX_FONT_NAME = FONT_FAMILY
LISTBOX_FONT_SIZE = 9

RECTANGLE_OUTLINE_COLOR_NORMAL = TEXT_DARK
RECTANGLE_OUTLINE_COLOR_SELECTED = SELECTED_OUTLINE
RECTANGLE_FILL_COLOR_ACTIVE = TEXT_LIGHT
RECTANGLE_FILL_COLOR_INACTIVE = TEXT_DARK
RECTANGLE_OUTLINE_WIDTH_NORMAL = 1
RECTANGLE_OUTLINE_WIDTH_SELECTED = 3
RECTANGLE_TEXT_COLOR = TEXT_DARK
RECTANGLE_FONT_NAME = FONT_FAMILY
RECTANGLE_FONT_SIZE = 10

DRAFT_RECT_OUTLINE_COLOR = SELECTED_OUTLINE
DRAFT_RECT_OUTLINE_WIDTH = 2
MIN_DRAG_DISTANCE = 3

PDF_SUMMARY_PAGE_MARGIN_X = 36
PDF_SUMMARY_PAGE_MARGIN_Y = 36
PDF_SUMMARY_PAGE_LINE_HEIGHT = 18
PDF_SUMMARY_PAGE_TITLE_HEIGHT = 26

UNDO_REDO_STACK_LIMIT = 10

SPINBOX_MIN_VALUE = 1
SPINBOX_MAX_VALUE = 100
SPINBOX_DEFAULT_VALUE = 1

CATALOGUE_WINDOW_WIDTH = 1200
CATALOGUE_WINDOW_HEIGHT = 500
CATALOGUE_WINDOW_MIN_WIDTH = 800
CATALOGUE_WINDOW_MIN_HEIGHT = 400
CATALOGUE_COLUMN_PADDING = 10
CATALOGUE_MAIN_PADDING = 20
CATALOGUE_WRAPLENGTH = 220

ASSETS_DIR = resource_path("App_TestData", "testdata_components", "assets")
LOGO1_PATH = str(ASSETS_DIR / "logo2.png")
LOGO2_PATH = str(ASSETS_DIR / "logo1.png")
PDF_WATERMARK_LOGO_PATH = str(ASSETS_DIR / "logo_marca_agua.png")
