"""Shared spacing and sizing tokens."""

HEADER_LOGO_SIZE = (280, 110)
HEADER_HEIGHT = 134
FOOTER_HEIGHT = 58
WINDOW_PAD = 24
SECTION_GAP = 12
CONTROL_GAP = 8
BUTTON_RADIUS = 0
CTK_RADIUS = BUTTON_RADIUS
CTK_ENTRY_HEIGHT = 30
CTK_COMPACT_BUTTON_SIZE = 24
