from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = PACKAGE_ROOT / "assets"
DIRECTORY_ICON_PATH = ASSETS_DIR / "logo2.png"
MINUS_ICON_PATH = ASSETS_DIR / "minus.png"
MINUS_ICON_HOVER_PATH = ASSETS_DIR / "minus_hover.png"
PLUS_ICON_PATH = ASSETS_DIR / "plus.png"
PLUS_ICON_HOVER_PATH = ASSETS_DIR / "plus_hover.png"
UP_ICON_PATH = ASSETS_DIR / "up.png"
UP_ICON_HOVER_PATH = ASSETS_DIR / "up_hover.png"
DOWN_ICON_PATH = ASSETS_DIR / "down.png"
DOWN_ICON_HOVER_PATH = ASSETS_DIR / "down_hover.png"
REMOVE_ICON_PATH = ASSETS_DIR / "x.png"
REMOVE_ICON_HOVER_PATH = ASSETS_DIR / "x_hover.png"

__all__ = [
    "ASSETS_DIR",
    "DIRECTORY_ICON_PATH",
    "MINUS_ICON_HOVER_PATH",
    "MINUS_ICON_PATH",
    "PACKAGE_ROOT",
    "PLUS_ICON_HOVER_PATH",
    "PLUS_ICON_PATH",
    "UP_ICON_HOVER_PATH",
    "UP_ICON_PATH",
    "DOWN_ICON_HOVER_PATH",
    "DOWN_ICON_PATH",
    "REMOVE_ICON_HOVER_PATH",
    "REMOVE_ICON_PATH",
]
